env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:react/recommended
globals:
  require: false
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true
    jsx: true
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-shadow:
    - warn
    - builtinGlobals: false
  semi: error
settings:
  react:
    version: detect
